CREATE DATABASE project;

CREATE TABLE StudentTable(
id INT PRIMARY KEY AUTO_INCREMENT,
user_id VARCHAR(50) UNIQUE,
`password` VARCHAR(50));


CREATE TABLE FacultyTable(
id INT PRIMARY KEY AUTO_INCREMENT,
user_id VARCHAR(50) UNIQUE,
`password` VARCHAR(50));
